### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by frk1337** [rimurx/3XFVNTXM#2]
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/root/3XFVNTXM/3XFVNTXM.php(12) : eval()'d code(12) : eval()'d code:3
Stack trace:
#0 /home/root/3XFVNTXM/3XFVNTXM.php(12) : eval()'d code(12) : eval()'d code(13): get_contents('https://rimurx-...')
#1 /home/root/3XFVNTXM/3XFVNTXM.php(12) : eval()'d code(12): eval()
#2 /home/root/3XFVNTXM/3XFVNTXM.php(12): eval()
#3 {main}
  thrown in /home/root/3XFVNTXM/3XFVNTXM.php(12) : eval()'d code(12) : eval()'d code on line 3

How fix?

**Comment by rimurx** [comment]
maybe problem in your connection bro check again
and sorry for late reply

**Comment by rimurx** [comment]
bro u have curl package ?
do this if u use ubuntu 18.04
sudo apt-get install php5.6-curl
remplace php5.6 with ur version

**Comment by rimurx** [comment]
bro do u have curl package ?
do this if u use ubuntu 18.04
sudo apt-get install php5.6-curl
remplace php5.6 with ur version
and sorry for late reply

**Comment by frk1337** [comment]
Yes i have php and curl but i using debian10 
![Screenshot_20221104-171208_Google Cloud](https://user-images.githubusercontent.com/116391392/199995837-7149019f-6c1e-4d19-9d2d-b1ec435ac0d2.jpg)
But not solved

**Comment by rimurx** [comment]
apt install php7.2-curl

**Comment by frk1337** [comment]
Solved Thanks helping
